# Syntax:
# https://docs.github.com/en/actions/creating-actions/metadata-syntax-for-github-actions
name: "Pipenv"
description: "Setup a Python virtual environment using the 'pipenv' tool."
author: "python@montmarquette.org"

inputs:
  python-version:
    description: "The specific Python version to use, else latest will be used"
    required: false
    default: "3.8"

runs:
  # https://docs.github.com/en/actions/creating-actions/metadata-syntax-for-github-actions#example-using-public-docker-registry-container
  #using: "docker"
  # image:
  # Can be 'Dockerfile' to use action-local Docker description file
  # or a link to an existing image e.g.: https://hub.docker.com/_/python/
  #image: "Dockerfile"
  #image: "docker://python:${{ inputs.python-version }}"
  #entrypoint: 'entrypoint.sh'
  using: "composite"
  steps:
    - run: |
        ls -Ralsh
      shell: sh
    - run: |
        docker build --file Dockerfile --build-arg PYTHON_VERSION=${{ inputs.python-version }} .
      shell: sh

# Branding:
# https://docs.github.com/en/actions/creating-actions/metadata-syntax-for-github-actions#branding
# https://feathericons.com/
branding:
  icon: "layers"
  color: "blue"
